# -*- coding: utf-8 -*-
"""프로젝트 1 청소년 건강데이터

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1THjgQizC4iCyY_QJyqRDfgnQKsMyHl_R
"""

!pkill -f streamlit
!pip install -q pyngrok

!pip install streamlit pyngrok

from pyngrok import ngrok

# 기존 열려있는 터널 닫기
ngrok.kill()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# # 1. 페이지 설정
# st.set_page_config(
#     page_title="청소년 수면시간 분석 앱",
#     page_icon="📱",
#     layout="wide"
# )
# 
# # 2. 웹 앱 상단 타이틀 및 설명
# st.title("📱 수면 부족 대한민국 청소년: 폰 때문일까, 학원 때문일까?")
# st.subheader("청소년 건강행태조사 데이터를 활용한 스마트폰 사용시간과 수면시간의 상관관계 탐색")
# st.markdown("""
# 스마트폰 사용시간이 늘어나면 정말 청소년들의 수면시간이 단축될까요?
# 이 웹 앱은 **청소년 건강행태조사 가상 데이터(100명)**를 기반으로 스마트폰 사용시간과 주중 수면시간 간의 인터랙티브한 관계를 분석합니다.
# 좌측 사이드바에서 원하는 학년을 선택하여 데이터를 비교해 보세요!
# """)
# 
# st.divider()
# 
# # 3. 데이터 불러오기 및 정제 함수
# @st.cache_data
# def load_and_clean_data():
#     df = pd.read_csv('survey_data_100.csv')
#     df_clean = df.dropna(subset=['수면시간', '스마트폰_사용시간']).copy()
#     valid_sleep = (df_clean['주중_평균_수면시간'] > 0) & (df_clean['주중_평균_수면시간'] < 24)
#     df_clean = df_clean[valid_sleep]
#     return df_clean
# 
# df_clean = load_and_clean_data()
# 
# # 4. 좌측 사이드바 - 학년 선택 필터
# st.sidebar.header("🔍 데이터 필터링")
# grade_options = ["전체"] + sorted([f"{g}학년" for g in df_clean['학년'].unique()])
# selected_grade = st.sidebar.selectbox("학년을 선택하세요", grade_options)
# 
# if selected_grade == "전체":
#     filtered_df = df_clean
# else:
#     grade_num = int(selected_grade.replace("학년", ""))
#     filtered_df = df_clean[df_clean['학년'] == grade_num]
# 
# # 5. 핵심 지표(st.metric) 영역
# col1, col2, col3 = st.columns(3)
# avg_sleep = filtered_df['주중_평균_수면시간'].mean()
# avg_phone = filtered_df['스마트폰_사용시간'].mean()
# sample_count = len(filtered_df)
# 
# col1.metric(label="📊 분석 대상 학생 수", value=f"{sample_count} 명")
# col2.metric(label="🌙 평균 수면시간", value=f"{avg_sleep:.2f} 시간")
# col3.metric(label="📲 평균 스마트폰 사용시간", value=f"{avg_phone:.2f} 시간")
# 
# st.divider()
# 
# # 6. Plotly 차트 시각화
# st.subheader(f"📈 [{selected_grade}] 스마트폰 사용시간 vs 수면시간 산점도")
# 
# fig = px.scatter(
#     filtered_df,
#     x='스마트폰_사용시간',
#     y='주중_평균_수면시간',
#     color='학년',
#     hover_data={
#         '학년': True,
#         '주중_평균_수면시간': ':.1f시간',
#         '스마트폰_사용시간': ':.1f시간'
#     },
#     template='plotly_white',
#     color_continuous_scale='Viridis'
# )
# 
# fig.update_layout(
#     font=dict(family='Malgun Gothic, NanumGothic, sans-serif', size=13),
#     xaxis_title='<b>스마트폰 사용시간 (시간)</b>',
#     yaxis_title='<b>주중 평균 수면시간 (시간)</b>',
#     height=500
# )
# 
# st.plotly_chart(fig, use_container_width=True)
# st.info("💡 **인사이트**: 스마트폰 사용시간과 수면시간 사이의 상관계수는 -0.055 수준으로 매우 낮습니다. 스마트폰 사용 외에 학원, 학업 스트레스 등 다른 생활요인이 수면시간에 더 큰 영향을 미치는지 함께 관찰해 보세요.")

import pandas as pd
import numpy as np

# 1. 데이터 불러오기
file_path = 'survey_data_100.csv'
df = pd.read_csv(file_path)

print("=== 1. 원본 데이터 확인 ===")
print(df.info())
print("\n결측치 수:\n", df.isnull().sum())

# 2. 데이터 정제 (Data Cleaning)
# (1) 중복 컬럼 제거 ('주중_평균_수면시간'과 '수면시간'이 동일하므로 하나 제거)
if '주중_평균_수면시간' in df.columns and '수면시간' in df.columns:
    df = df.drop(columns=['주중_평균_수면시간'])

# (2) 이상치(Outlier) 정제: 수면시간이 0시간 미만이거나 24시간 초과인 데이터 NaN 처리
df.loc[(df['수면시간'] < 0) | (df['수면시간'] > 24), '수면시간'] = np.nan

# 이상치를 중앙값 또는 평균값으로 채우기 (여기서는 수면시간 평균값 사용)
mean_sleep = df['수면시간'].mean()
df['수면시간'] = df['수면시간'].fillna(mean_sleep)

# (3) 결측치(Missing Value) 처리: 스마트폰 사용시간 결측치는 중앙값으로 대체
median_phone = df['스마트폰_사용시간'].median()
df['스마트폰_사용시간'] = df['스마트폰_사용시간'].fillna(median_phone)

print("\n=== 2. 정제 후 데이터 확인 ===")
print("정제 후 결측치 수:\n", df.isnull().sum())

# 3. 데이터 요약 및 분석 (Summary)
print("\n=== 3. 전체 데이터 기술통계 요약 ===")
summary_stats = df.describe()
print(summary_stats.round(2))

print("\n=== 4. 학년별 수면시간 및 스마트폰 사용시간 평균 ===")
group_summary = df.groupby('학년')[['수면시간', '스마트폰_사용시간']].mean()
print(group_summary.round(2))

import pandas as pd

# 1. 데이터 불러오기
file_path = 'survey_data_100.csv'
df = pd.read_csv(file_path)

# 2. 데이터 자동 정제
# 규칙 1: 수면시간 및 스마트폰_사용시간 컬럼에 결측치(NaN)가 있는 행 제거
df_clean = df.dropna(subset=['수면시간', '스마트폰_사용시간']).copy()

# 규칙 2: 주중_평균_수면시간이 0시간 이하이거나 24시간 이상인 이상치 행 제거
valid_sleep_condition = (df_clean['주중_평균_수면시간'] > 0) & (df_clean['주중_평균_수면시간'] < 24)
df_clean = df_clean[valid_sleep_condition]

# 3. 정제 결과 확인
print(f"전처리 전 데이터 건수: {len(df)}건")
print(f"전처리 후 데이터 건수: {len(df_clean)}건 (총 {len(df) - len(df_clean)}건 제거됨)\n")

# 4. 정제된 데이터 요약 통계
print("=== 정제된 데이터 기술통계 요약 ===")
print(df_clean.describe().round(2))

# 5. 학년별 요약
print("\n=== 학년별 수면시간 및 스마트폰 사용시간 평균 ===")
print(df_clean.groupby('학년')[['수면시간', '스마트폰_사용시간']].mean().round(2))

# '학년' 기준 그룹화 및 평균 계산 (소수점 둘째 자리 반올림)
grade_summary = df_clean.groupby('학년')[['수면시간', '스마트폰_사용시간']].mean().round(2)

# 컬럼명 정리
grade_summary.columns = ['평균 수면시간', '평균 스마트폰 사용시간']

print(grade_summary)

# ==============================================================================
# [청소년 건강행태조사 데이터 정제 및 요약 분석]
# 구글 코랩(Google Colab)에서 그대로 실행할 수 있는 전체 코드입니다.
# ==============================================================================

# 1. 필요한 라이브러리 불러오기
import pandas as pd  # 데이터 분석 및 조작을 위한 대표적인 도구
import numpy as np   # 숫자 계산 및 수치 처리를 돕는 도구

# 2. CSV 데이터 파일 불러오기
# 'survey_data_100.csv' 파일을 읽어와서 df라는 변수에 저장합니다.
file_path = 'survey_data_100.csv'
df = pd.read_csv(file_path)

# 3. 데이터 정제 (Data Cleaning)
# 규칙 1: '수면시간' 또는 '스마트폰_사용시간'에 빈 값(NaN)이 있는 줄(행)을 지웁니다.
df_clean = df.dropna(subset=['수면시간', '스마트폰_사용시간']).copy()

# 규칙 2: '주중_평균_수면시간'이 0시간 이하이거나 24시간 이상인 비현실적 데이터(이상치)를 제외합니다.
valid_sleep_condition = (df_clean['주중_평균_수면시간'] > 0) & (df_clean['주중_평균_수면시간'] < 24)
df_clean = df_clean[valid_sleep_condition]

# 4. 학년별 데이터 그룹화 및 평균 계산
# '학년'별로 그룹을 묶고, '수면시간'과 '스마트폰_사용시간'의 평균을 계산합니다.
grouped_data = df_clean.groupby('학년')[['수면시간', '스마트폰_사용시간']].mean()

# 5. 소수점 둘째 자리까지 반올림
grouped_data = grouped_data.round(2)

# 6. 보기 편하도록 표의 컬럼(열) 이름 변경하기
grouped_data.columns = ['평균 수면시간(시간)', '평균 스마트폰 사용시간(시간)']

# 7. 최종 분석 결과 출력
print("========================================")
print("       학년별 요약 분석 결과 표        ")
print("========================================")
print(grouped_data)

import pandas as pd
import numpy as np

# 1. 데이터 파일 불러오기
file_path = 'survey_data_100.csv'
df = pd.read_csv(file_path)

# 2. 데이터 정제 (Data Cleaning)
# 규칙 1: '수면시간' 또는 '스마트폰_사용시간'에 빈 값(NaN)이 있는 행 지우기
df_clean = df.dropna(subset=['수면시간', '스마트폰_사용시간']).copy()

# 규칙 2: '주중_평균_수면시간'이 0시간 이하이거나 24시간 이상인 이상치 제외하기 (컬럼명 오타 수정 완료)
valid_sleep_condition = (df_clean['주중_평균_수면시간'] > 0) & (df_clean['주중_평균_수면시간'] < 24)
df_clean = df_clean[valid_sleep_condition]

# 3. 학년별 데이터 그룹화 및 평균 계산
grouped_data = df_clean.groupby('학년')[['수면시간', '스마트폰_사용시간']].mean()

# 4. 소수점 둘째 자리까지 반올림
grouped_data = grouped_data.round(2)

# 5. 보기 편하도록 표의 컬럼 이름 변경하기
grouped_data.columns = ['평균 수면시간(시간)', '평균 스마트폰 사용시간(시간)']

# 6. 최종 분석 결과 출력
print("========================================")
print("       학년별 요약 분석 결과 표        ")
print("========================================")
print(grouped_data)

import pandas as pd
import plotly.express as px

# 1. 데이터 불러오기 및 정제
df = pd.read_csv('survey_data_100.csv')

# 결측치 제거 및 이상치 제거 (기존 정제 규칙)
df_clean = df.dropna(subset=['수면시간', '스마트폰_사용시간']).copy()
valid_sleep = (df_clean['주중_평균_수면시간'] > 0) & (df_clean['주중_평균_수면시간'] < 24)
df_clean = df_clean[valid_sleep]

# 2. Plotly 산점도(Scatter Plot) 생성
fig = px.scatter(
    df_clean,
    x='스마트폰_사용시간',            # X축
    y='주중_평균_수면시간',           # Y축
    color='학년',                     # 점 색상 (학년별 구분)
    hover_data={                      # 마우스 올려놓았을 때 팝업(hover) 정보
        '학년': True,
        '주중_평균_수면시간': ':.1f시간',
        '스마트폰_사용시간': ':.1f시간'
    },
    title='<b>청소년 수면시간 vs 스마트폰 사용시간 산점도</b>',
    template='plotly_white',          # 깔끔한 라이브러리 테마 (다크 원할 시 'plotly_dark')
    color_continuous_scale='Viridis'  # 색상 팔레트 설정
)

# 3. 레이아웃 및 한글 폰트 설정
fig.update_layout(
    font=dict(family='Malgun Gothic, NanumGothic, sans-serif', size=13),
    xaxis_title='<b>스마트폰 사용시간 (시간)</b>',
    yaxis_title='<b>주중 평균 수면시간 (시간)</b>',
    title_font_size=18,
    hoverlabel=dict(bgcolor="white", font_size=13)
)

# 4. 차트 출력
fig.show()

import streamlit as st
import pandas as pd
import plotly.express as px

# 1. 페이지 설정
st.set_page_config(
    page_title="청소년 수면시간 분석 앱",
    page_icon="📱",
    layout="wide"
)

# 2. 웹 앱 상단 타이틀 및 설명
st.title("📱 수면 부족 대한민국 청소년: 폰 때문일까, 학원 때문일까?")
st.subheader("청소년 건강행태조사 데이터를 활용한 스마트폰 사용시간과 수면시간의 상관관계 탐색")
st.markdown("""
스마트폰 사용시간이 늘어나면 정말 청소년들의 수면시간이 단축될까요?
이 웹 앱은 **청소년 건강행태조사 가상 데이터(100명)**를 기반으로 스마트폰 사용시간과 주중 수면시간 간의 인터랙티브한 관계를 분석합니다.
좌측 사이드바에서 원하는 학년을 선택하여 데이터를 비교해 보세요!
""")

st.divider()

# 3. 데이터 불러오기 및 정제 함수 (캐싱 적용)
@st.cache_data
def load_and_clean_data():
    # 데이터 읽기
    df = pd.read_csv('survey_data_100.csv')

    # 규칙 1: 수면시간 및 스마트폰_사용시간 결측치 제거
    df_clean = df.dropna(subset=['수면시간', '스마트폰_사용시간']).copy()

    # 규칙 2: 주중_평균_수면시간 이상치(0 이하 또는 24 이상) 제거
    valid_sleep = (df_clean['주중_평균_수면시간'] > 0) & (df_clean['주중_평균_수면시간'] < 24)
    df_clean = df_clean[valid_sleep]

    return df_clean

# 데이터 로드
df_clean = load_and_clean_data()

# 4. 좌측 사이드바 - 학년 선택 필터
st.sidebar.header("🔍 데이터 필터링")

# 학년 옵션 생성 (전체 + 존재하는 학년 목록)
grade_options = ["전체"] + sorted([f"{g}학년" for g in df_clean['학년'].unique()])
selected_grade = st.sidebar.selectbox("학년을 선택하세요", grade_options)

# 선택에 따른 데이터 필터링
if selected_grade == "전체":
    filtered_df = df_clean
else:
    grade_num = int(selected_grade.replace("학년", ""))
    filtered_df = df_clean[df_clean['학년'] == grade_num]

# 5. 핵심 지표(st.metric) 영역
col1, col2, col3 = st.columns(3)

avg_sleep = filtered_df['주중_평균_수면시간'].mean()
avg_phone = filtered_df['스마트폰_사용시간'].mean()
sample_count = len(filtered_df)

col1.metric(label="📊 분석 대상 학생 수", value=f"{sample_count} 명")
col2.metric(label="🌙 평균 수면시간", value=f"{avg_sleep:.2f} 시간")
col3.metric(label="📲 평균 스마트폰 사용시간", value=f"{avg_phone:.2f} 시간")

st.divider()

# 6. Plotly 인터랙티브 차트 시각화
st.subheader(f"📈 [{selected_grade}] 스마트폰 사용시간 vs 수면시간 산점도")

fig = px.scatter(
    filtered_df,
    x='스마트폰_사용시간',
    y='주중_평균_수면시간',
    color='학년',
    hover_data={
        '학년': True,
        '주중_평균_수면시간': ':.1f시간',
        '스마트폰_사용시간': ':.1f시간'
    },
    template='plotly_white',
    color_continuous_scale='Viridis'
)

fig.update_layout(
    font=dict(family='Malgun Gothic, NanumGothic, sans-serif', size=13),
    xaxis_title='<b>스마트폰 사용시간 (시간)</b>',
    yaxis_title='<b>주중 평균 수면시간 (시간)</b>',
    height=500
)

# Streamlit에 Plotly 차트 렌더링
st.plotly_chart(fig, use_container_width=True)

# 7. 데이터 요약 안내
st.info("💡 **인사이트**: 스마트폰 사용시간과 수면시간 사이의 상관계수는 -0.055 수준으로 매우 낮습니다. 스마트폰 사용 외에 학원, 학업 스트레스 등 다른 생활요인이 수면시간에 더 큰 영향을 미치는지 함께 관찰해 보세요.")

import os
import re
import subprocess
import time

# 1. 이전 실행 프로세스 정리
os.system("pkill -f streamlit")
os.system("pkill -f cloudflared")

# 2. cloudflared 다운로드 (1회성)
if not os.path.exists("cloudflared"):
    os.system("wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared")
    os.system("chmod +x cloudflared")

# 3. app.py 파일 생성
app_code = """
import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="청소년 수면시간 분석 앱", layout="wide")
st.title("📱 수면 부족 대한민국 청소년: 폰 때문일까, 학원 때문일까?")
st.subheader("청소년 건강행태조사 데이터를 활용한 분석")

@st.cache_data
def load_data():
    df = pd.read_csv('survey_data_100.csv')
    df_clean = df.dropna(subset=['수면시간', '스마트폰_사용시간']).copy()
    valid_sleep = (df_clean['주중_평균_수면시간'] > 0) & (df_clean['주중_평균_수면시간'] < 24)
    return df_clean[valid_sleep]

df_clean = load_data()

st.sidebar.header("🔍 데이터 필터링")
grade_options = ["전체"] + sorted([f"{g}학년" for g in df_clean['학년'].unique()])
selected_grade = st.sidebar.selectbox("학년을 선택하세요", grade_options)

if selected_grade == "전체":
    filtered_df = df_clean
else:
    grade_num = int(selected_grade.replace("학년", ""))
    filtered_df = df_clean[df_clean['학년'] == grade_num]

col1, col2, col3 = st.columns(3)
col1.metric("📊 분석 대상 학생 수", f"{len(filtered_df)} 명")
col2.metric("🌙 평균 수면시간", f"{filtered_df['주중_평균_수면시간'].mean():.2f} 시간")
col3.metric("📲 평균 스마트폰 사용시간", f"{filtered_df['스마트폰_사용시간'].mean():.2f} 시간")

st.divider()
st.subheader(f"📈 [{selected_grade}] 스마트폰 사용시간 vs 수면시간 산점도")

fig = px.scatter(
    filtered_df, x='스마트폰_사용시간', y='주중_평균_수면시간', color='학년',
    hover_data={'학년': True, '주중_평균_수면시간': ':.1f시간', '스마트폰_사용시간': ':.1f시간'},
    template='plotly_white', color_continuous_scale='Viridis'
)
fig.update_layout(xaxis_title='스마트폰 사용시간(시간)', yaxis_title='주중 평균 수면시간(시간)', height=500)
st.plotly_chart(fig, use_container_width=True)
st.info("💡 인사이트: 두 변수의 상관계수는 -0.055로 거의 상관관계가 없습니다.")
"""

with open("app.py", "w", encoding="utf-8") as f:
    f.write(app_code)

# 4. Streamlit 백그라운드 구동
subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501", "--server.address", "0.0.0.0"])
time.sleep(3)

# 5. Cloudflare Tunnel 구동 및 URL 안전 추출
print("==================================================")
print("⌛ 웹 접속 주소를 생성 중입니다 (약 3~5초 소요)...")
print("==================================================")

proc = subprocess.Popen(["./cloudflared", "tunnel", "--url", "http://localhost:8501"], stderr=subprocess.PIPE, text=True)

while True:
    line = proc.stderr.readline()
    match = re.search(r"https://[a-zA-Z0-9-]+\.trycloudflare\.com", line)
    if match:
        url = match.group(0)
        print("\n🎉 아래 링크를 클릭하시면 웹 앱이 즉시 열립니다:")
        print(f"👉 {url}\n")
        break

import os
import re
import subprocess
import time

# 1. 기존 실행 프로세스 정리
os.system("pkill -f streamlit")
os.system("pkill -f cloudflared")

# 2. cloudflared 다운로드
if not os.path.exists("cloudflared"):
    os.system("wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared")
    os.system("chmod +x cloudflared")

# 3. 데이터 파일이 없는 경우를 대비해 샘플 CSV 자동 생성
import pandas as pd
import numpy as np

if not os.path.exists("survey_data_100.csv"):
    np.random.seed(42)
    sample_data = {
        '학년': np.random.choice([1, 2, 3], size=100),
        '스마트폰_사용시간': np.round(np.random.uniform(1, 8, size=100), 1),
        '주중_평균_수면시간': np.round(np.random.uniform(4, 9, size=100), 1),
        '수면시간': np.round(np.random.uniform(4, 9, size=100), 1)
    }
    pd.DataFrame(sample_data).to_csv('survey_data_100.csv', index=False, encoding='utf-8-sig')

# 4. 안전하게 보정된 app.py 파일 작성
app_code = """
import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="청소년 수면시간 분석 앱", layout="wide")
st.title("📱 수면 부족 대한민국 청소년: 폰 때문일까, 학원 때문일까?")
st.subheader("청소년 건강행태조사 데이터를 활용한 분석")

@st.cache_data
def load_data():
    try:
        df = pd.read_csv('survey_data_100.csv')
    except Exception as e:
        st.error("데이터 파일을 읽을 수 없습니다.")
        return pd.DataFrame()

    # 컬럼명 유연하게 매핑
    sleep_col = None
    for col in ['주중_평균_수면시간', '수면시간']:
        if col in df.columns:
            sleep_col = col
            break

    if not sleep_col or '스마트폰_사용시간' not in df.columns:
        st.error("CSV 파일에 '스마트폰_사용시간' 또는 '수면시간' 컬럼이 없습니다.")
        return pd.DataFrame()

    df['주중_평균_수면시간'] = df[sleep_col]
    df_clean = df.dropna(subset=['주중_평균_수면시간', '스마트폰_사용시간']).copy()
    valid_sleep = (df_clean['주중_평균_수면시간'] > 0) & (df_clean['주중_평균_수면시간'] < 24)
    return df_clean[valid_sleep]

df_clean = load_data()

if df_clean.empty:
    st.warning("표시할 데이터가 없습니다.")
else:
    st.sidebar.header("🔍 데이터 필터링")
    grade_options = ["전체"] + sorted([f"{g}학년" for g in df_clean['학년'].unique()])
    selected_grade = st.sidebar.selectbox("학년을 선택하세요", grade_options)

    if selected_grade == "전체":
        filtered_df = df_clean
    else:
        grade_num = int(selected_grade.replace("학년", ""))
        filtered_df = df_clean[df_clean['학년'] == grade_num]

    col1, col2, col3 = st.columns(3)
    col1.metric("📊 분석 대상 학생 수", f"{len(filtered_df)} 명")
    col2.metric("🌙 평균 수면시간", f"{filtered_df['주중_평균_수면시간'].mean():.2f} 시간")
    col3.metric("📲 평균 스마트폰 사용시간", f"{filtered_df['스마트폰_사용시간'].mean():.2f} 시간")

    st.divider()
    st.subheader(f"📈 [{selected_grade}] 스마트폰 사용시간 vs 수면시간 산점도")

    fig = px.scatter(
        filtered_df,
        x='스마트폰_사용시간',
        y='주중_평균_수면시간',
        color='학년',
        hover_data={'학년': True, '주중_평균_수면시간': ':.1f시간', '스마트폰_사용시간': ':.1f시간'},
        template='plotly_white',
        color_continuous_scale='Viridis'
    )
    fig.update_layout(
        xaxis_title='스마트폰 사용시간(시간)',
        yaxis_title='주중 평균 수면시간(시간)',
        height=500
    )
    st.plotly_chart(fig, use_container_width=True)
    st.info("💡 인사이트: 두 변수의 상관계수를 확인해 보세요.")
"""

with open("app.py", "w", encoding="utf-8") as f:
    f.write(app_code)

# 5. Streamlit 구동
subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501", "--server.address", "0.0.0.0"])
time.sleep(3)

# 6. Cloudflare Tunnel 접속 링크 생성
print("==================================================")
print("⌛ 접속 링크 생성 중...")
print("==================================================")

proc = subprocess.Popen(["./cloudflared", "tunnel", "--url", "http://localhost:8501"], stderr=subprocess.PIPE, text=True)

while True:
    line = proc.stderr.readline()
    match = re.search(r"https://[a-zA-Z0-9-]+\.trycloudflare\.com", line)
    if match:
        url = match.group(0)
        print("\n🎉 아래 링크를 클릭하면 산점도가 포함된 웹 앱이 열립니다:")
        print(f"👉 {url}\n")
        break